version: "3"

services:
    docsify:
      container_name: docsify
      hostname: docsify
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ${PWD}/docs:/docs
      ports:
        - 3000:3000
      command: docsify serve /docs
